### ISSUE TITLE
Ruby Group Capstone Project

### ISSUE THREAD

**Issue by mmatongo** [mmatongo/catalog-of-my-things#29]
This group is composed of the following members:
- `Team Member 1` => @Kalunge 
- `Team Member 2` => @julie-ify 
- `Team Member 3` => @mmatongo 
- `Team Member 4` => @ridaarif98 

Project Board => [Kanban Board](https://github.com/mmatongo/catalog-of-my-things/projects/1)

**Comment by omar-labana** [comment]
Hi team, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Kindly add a description for each task.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmatongo** [comment]
> ## Required Changes ♻️
> * [X]  Kindly add a description for each task.

Done

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmatongo** [comment]
> Hi Team,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it 🚀 : Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏


Thanks
